
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int JLT = 19;
  public static final int PUSH_VAR = 9;
  public static final int MOD = 6;
  public static final int CALL = 14;
  public static final int PUSH_INT = 8;
  public static final int SET_ARG = 13;
  public static final int RETURN = 16;
  public static final int DOIS_PONTOS = 26;
  public static final int STORE_VAR = 10;
  public static final int PRINT_STR = 21;
  public static final int INTEIRO = 24;
  public static final int EXP = 7;
  public static final int PUSH_ARG = 11;
  public static final int SUB = 3;
  public static final int STRING = 25;
  public static final int JUMP = 17;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int PRINT_NL = 22;
  public static final int DIV = 5;
  public static final int ADD = 2;
  public static final int JEQ = 18;
  public static final int PRINT = 20;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 23;
  public static final int STORE_ARG = 12;
  public static final int ERRO = 27;
  public static final int LOCALS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "MOD",
  "EXP",
  "PUSH_INT",
  "PUSH_VAR",
  "STORE_VAR",
  "PUSH_ARG",
  "STORE_ARG",
  "SET_ARG",
  "CALL",
  "LOCALS",
  "RETURN",
  "JUMP",
  "JEQ",
  "JLT",
  "PRINT",
  "PRINT_STR",
  "PRINT_NL",
  "IDENTIFICADOR",
  "INTEIRO",
  "STRING",
  "DOIS_PONTOS",
  "ERRO"
  };
}

